name: 'Validate Commit'

on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]

jobs:
  validate-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Format
        run: yarn format

      - name: Test
        run: yarn coverage

      - name: Build
        run: yarn build
